<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sony-PC" ignored="0" name="Nopackage" tests="12" failures="1" timestamp="25 Sep 2021 06:06:20 GMT" time="1.544" errors="0">
  <testcase name="function1" time="0.016" classname="Sample.TestCase1"/>
  <testcase name="function1" time="0.0" classname="Sample.TestCase1"/>
  <testcase name="function1" time="0.0" classname="Sample.TestCase1"/>
  <testcase name="function1" time="0.0" classname="Sample.TestCase1"/>
  <testcase name="function1" time="0.0" classname="Sample.TestCase1"/>
  <testcase name="function1" time="0.0" classname="Sample.TestCase1"/>
  <testcase name="function1" time="0.0" classname="Sample.TestCase1"/>
  <testcase name="function1" time="0.0" classname="Sample.TestCase1"/>
  <testcase name="function1" time="0.0" classname="Sample.TestCase1"/>
  <testcase name="function1" time="0.0" classname="Sample.TestCase1"/>
  <testcase name="function2" time="1.466" classname="Sample.TestCase1">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method Sample.TestCase1.function2() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method Sample.TestCase1.function2() didn't finish within the time-out 1000
]]>
    </failure>
  </testcase> <!-- function2 -->
  <testcase name="function3" time="0.0" classname="Sample.TestCase1"/>
</testsuite> <!-- Nopackage -->
