-------------------------------------------------------------------------------
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.011 s <<< FAILURE! - in TestSuite
Sample.TestCase1.function2  Time elapsed: 1.357 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method Sample.TestCase1.function2() didn't finish within the time-out 1000

